### ISSUE TITLE
Obsidian Links Support?

### ISSUE THREAD

**Issue by herbertnikolajewskidci** [GoyoStach/Obsidian-to-Astro#2]
hey,

I love your work. I've been looking for something like what you did for months and now I've stumbled across your work! 😍

I wanted to ask if you managed to get obsidian links to convert correctly? So in something like this:

`[[Obsidian-Link]] -> <a>Obsidian link</a>`

Do you understand what I mean?

I created a fork of your repo and tried it on my local and unfortunately it doesn't recognize it correctly and outputs it just like that:

`[[Obsidian-Link]] -> [[Obsidian-Link]]`

I'm looking forward to your response!

**Comment by Goyostash** [comment]
Hello, sorry for only seeing you issue today... 

First of all thanks for the compliment !

If i am understanding correctly you would want to go from one blog post to another on your website while maintaining your obsidian links.

I did not actually think about this issue, when I am referencing link I usually redirect from the final link in my obsidian note.

`[Advise for life](Permanent%20Notes/Advise%20for%20life.md) --> [Advice for life](https://obsidian-to-astro.vercel.app/Obsidian-Posts/Advise%20for%20life)`

Although it diminish the usability of obsidian on its own as you wont be able to go to the note directly and have fast hyperlink.

Most of my notes are independent which is why this issue does not really bother me. 

You might be able to fix this issue with a small program to parse your path in your markdown files and adding the base url of your site when needed to reference other blog posts.

I hope it helps.

Best regards

**Comment by Goyostash** [comment]
I will close the issue as this development is not on the way.

**Comment by stereobooster** [comment]
One of the ways to support wikilinks https://astro-digital-garden.stereobooster.com/recipes/wikilinks/

Also related discussion https://github.com/withastro/starlight/discussions/1113
